# -*- coding: utf-8 -*-
"""WEB SCRAPING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzWOiXricUK7w4SR-10zmEoBX6nlRd2k
"""

#web scraping - Extracting/Scraping data from the web
#Here let us scrape Amazon Customer reviews
#Tool used here is - Beautiful Soup

#url- https://www.amazon.in/Apple-iPhone-14-128GB-Blue/product-reviews/B0BDK62PDX/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews

#we are importing different libraries
import requests
from bs4 import BeautifulSoup as bs

url= 'https://www.amazon.in/Apple-iPhone-14-128GB-Blue/product-reviews/B0BDK62PDX/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews'
page = requests.get(url)  #we are requesting for the url's web page
page


#<Response [503]> is an error, <Response [200]> is right
#try re running ur cell 5 - 10 times, if error exists then check ur url

page.content

#let us organize the above source code and print it in better readible format
soup=bs(page.content,'html.parser')
soup #html.parser is better readable format of source code

#never consider top positive and top critical reviews

#let us extract the Amazon customer review names
names = soup.find_all('span',class_ =  'a-profile-name')[2:] #a-profile-name is the inspected from the source code
names

len(names)  #variable names is a list and it has 9 elememts

import pandas as pd
df = pd.DataFrame(names,columns = ['Customer Names'])
df



df=df.drop_duplicates(ignore_index=True)
df

#next let us just scrape the review title
r_title = soup.find_all('a',class_='review-title')
r_title

len(r_title)

#Data filtering/ Daata cleaning
review_title = [] #emplty list
#for i  in range (0,10)
for i in range(0,len(r_title)):
  review_title.append(r_title[i].get_text())
review_title

#next is review date
dates = soup.find_all('span',class_='review-date')
dates

len(dates)

#Data filtering/ Daata cleaning
review_date = [] #emplty list
#for i  in range (0,10)
for i in range(0,len(dates)):
  review_date.append(dates[i].get_text().replace('Reviewed in India 🇮🇳 on',''))
review_date

